### ISSUE TITLE
No checkpoint file found at [.....] ?

### ISSUE THREAD

**Issue by ghaidaahmed** [priyanshugandhi/priyanshu-face_recognition#2]
hello, 
thank you for the nice work.   I have problem when I run `streaming_main`, I follow the instructions but when I run I see this `No checkpoint file found at [/Users/ghaida/Downloads/priyanshu-face_recognition-master/inception/22801 ]`, I install the fails from google drive.
 any help please?

**Comment by priyanshugandhi** [comment]
Download the Inception model. You can find it at any online sources.
